-keep class com.google.firebase.** { *; }
-keep class com.google.mlkit.** { *; }
-dontwarn com.google.firebase.iid.**
-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**